install.packages("fivethirtyeight")
install.packages("formattable")

library(fivethirtyeight)

data("classic_rock_raw_data")
data("classic_rock_song_list")


library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(formattable)



```{r}
radio <- classic_rock_raw_data %>% group_by(callsign) %>% count(callsign) %>% arrange(desc(n)) %>% rename("songs played" = n)
formattable(radio, align = c("l","r"))
```

```{r}
song <- classic_rock_raw_data %>% group_by(song) %>% count(song) %>% arrange(desc(n)) %>% filter(n >= 134) %>% rename("times played" = n)
formattable(song, align = c("l","r"))
```


```{r}
artist <- classic_rock_raw_data %>% group_by(artist) %>% count(artist) %>% arrange(desc(n)) %>% filter(n >= 965)
ggplot(artist, aes(x= reorder(artist, n), y = n, fill = artist)) + geom_bar(stat = 'identity') + coord_flip() + theme_minimal() + scale_fill_brewer(palette = "YlOrRd") + ggtitle("Most Played Artists on the Radio") + labs(y = "Times Played", x = "Artist")
```


```{r}
songs_by_radio <- classic_rock_raw_data %>% group_by(callsign) %>% count(song) %>% arrange(desc(n)) %>% filter(n >= 13)
ggplot(songs_by_radio, aes(x= reorder(song, n), y = n, fill = callsign)) + geom_bar(stat = 'identity') + coord_flip() + theme_minimal() + scale_fill_brewer(palette = "YlOrRd") + ggtitle("Most Common Song and Station Combination") + labs(y = "Times Played", x = "Song")
```


```{r}
artists_by_radio <- classic_rock_raw_data %>% group_by(callsign) %>% count(artist) %>% arrange(desc(n)) %>% filter(n >= 90)
ggplot(artists_by_radio, aes(x= reorder(artist, n), y = n, fill = callsign)) + geom_bar(stat = 'identity') + coord_flip() + theme_minimal() + scale_fill_brewer(palette = "YlOrRd") + ggtitle("Most Common Song and Artist Combination") + labs(y = "Times Played", x = "Artist")
```

```{r}
top_KSEG <- classic_rock_raw_data %>% filter(callsign == "KSEG") %>% group_by(song) %>% count(song) %>% arrange(desc(n)) %>% filter(n>=7) %>% rename("times played" = n)

formattable(top_KSEG, align = c("l","r"))

```


```{r}
top_WXGL <- classic_rock_raw_data %>% filter(callsign == "WXGL") %>% group_by(song) %>% count(song) %>% arrange(desc(n)) %>% filter(n>=12) %>% rename("times played" = n)

formattable(top_WXGL, align = c("l","r"))

```




```{r}
top_WCSX <- classic_rock_raw_data %>% filter(callsign == "WCSX") %>% group_by(song) %>% count(song) %>% arrange(desc(n)) %>% filter(n>=11) %>% rename("times played" = n)

formattable(top_WCSX, align = c("l","r"))
```


```{r}
top_artist_KSEG <- classic_rock_raw_data %>% filter(callsign == "KSEG") %>% group_by(artist) %>% count(artist) %>% arrange(desc(n)) %>% filter(n>= 50)

ggplot(top_artist_KSEG, aes(x = reorder(artist, n), y = n, fill = artist)) + geom_bar(stat = "identity") + coord_flip() + theme_minimal() + scale_fill_brewer(palette = "YlOrRd") + ggtitle("Most Popular Artists on KSEG") + labs(y = "Times Played", x = "Artist")
```





```{r}
top_artist_WXGL <- classic_rock_raw_data %>% filter(callsign == "WXGL") %>% group_by(artist) %>% count(artist) %>% arrange(desc(n)) %>% filter(n>=69)

ggplot(top_artist_WXGL, aes(x = reorder(artist, n), y = n, fill = artist)) + geom_bar(stat = "identity") + coord_flip() + theme_minimal() + scale_fill_brewer(palette = "YlOrRd") + ggtitle("Most Popular Artists on WXGL") + labs(y = "Times Played", x = "Artist")
```




```{r}
top_artist_WCSX <- classic_rock_raw_data %>% filter(callsign == "WCSX") %>% group_by(artist) %>% count(artist) %>% arrange(desc(n)) %>% filter(n>=48)

ggplot(top_artist_WCSX, aes(x = reorder(artist, n), y = n, fill = artist)) + geom_bar(stat = "identity") + coord_flip() + theme_minimal() + scale_fill_brewer(palette = "YlOrRd") + ggtitle("Most Popular Artists on WCSX") + labs(y = "Times Played", x = "Artist")
```
